package calc;

import java.util.Scanner;

      public class Main {
    	
    public static void main(String[] args){
    	   
    	int a,b;
  		
		System.out.println("Enter The Values To Your Calc to add,subtract,multiply and divide your number");
		 System.out.println("Enter the Second value Except 0");
		  @SuppressWarnings("resource")
	  		Scanner scn = new Scanner(System.in);
	  		  a = scn.nextInt();
	  		  b = scn.nextInt();
	  		  
	  	Thread t1=new Thread(){
	 			 public   void run()
	 				{
	 				 try
	 				 {
	 					
	 					 sleep(1000);
	 					
	 				 int c;
	 			     c=a+b;
	 			     System.out.println("The Result for Addition is:"+c);
	 				 }
	 				 catch(InterruptedException e)
	 				 {
	 					 System.out.println(e);
	 				 }
	 			     
	 				}
	 		};
	 		
	 		
	 	 Thread t2=new Thread(){
				 public   void run()
					{
					 try
	 				 {
						
	 					 sleep(1000);
	 				 
					 int c;
				     c=a-b;
				     System.out.println("The Result for subtraction is:"+c);
					}
					 
 				 catch(InterruptedException e)
 				 {
 					 System.out.println(e);
 				 }
					}
			};
			
			
			
			
			 Thread t3=new Thread(){
				 public   void run()
					{
					 try
	 				 {
						
	 					 sleep(1000);
	 				 
					 int c;
				     c=a*b;
				     System.out.println("The Result for multiplication is:"+c);
					}
					 
 				 catch(InterruptedException e)
 				 {
 					 System.out.println(e);
 				 }
					}
			};
			
			
			
			
			
			Thread t4=new Thread(){
				 public   void run()
					{
					 try
	 				 {
						
	 					 sleep(1000);
	 				 
					 int c;
				     c=a/b;
				     System.out.println("The Result for Division is:"+c);
					}
					 
				 catch(InterruptedException e)
				 {
					 System.out.println(e);
				 }
					 catch(ArithmeticException e)
					 {
						 System.out.println(e);
						
						 
					 }
					}
			};
			
			
	
	
		t1.start();
		
		try
		{
		t1.join();
		}
		catch(Exception e)
		{
			System.out.println(e);
		}
		
		
		t2.start();
		
		
		try
		{
		t2.join();
		}
		catch(Exception e)
		{
			System.out.println(e);
		}
		
		
		t3.start();
		
		
		try
		{
		t3.join();
		}
		catch(Exception e)
		{
			System.out.println(e);
		}
		
		
		
		t4.start();
		
		
		
		
	}
}      

